# Generated by Django 4.2.7 on 2023-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tarmada.com%2Frestaurants&psig=AOvVaw0AoqcHZUhFzEW7-MhvGsUX&ust=1699778195164000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCOj-ia7Fu4IDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
